<link href="table.css" rel="stylesheet" type="text/css" />
<center>
<table summary="Submitted table designs"><caption>Lista de telefones cadastrados&nbsp;&nbsp;&nbsp;&nbsp;<a href="cadlista.php" title="Cadastrar"><image src="iadd.png" width="25px" heigth="25px"></a>&nbsp;&nbsp;&nbsp;<a href="sms.php" title="SMS"><image src="isms.png" width="25px" heigth="25px"></a></caption><thead><tr><th scope="col">LISTA</th><th scope="col">OPERADORA</th><th scope="col">DDD</th><th scope="col">TELEFONE</th><th scope="col">Ações</th></tr></thead>
<tfoot><tr><th scope="row">Total</th><td colspan="4">7 registros</td></tr></tfoot>
<tbody>
<tr><th id="r100" scope="row">SALA TÉCNICA</th><td>OI</td><td>092</td><td>88888888</td><td><a href="delete.php" title="Excluir"><image src="idelete.png" width="25px" heigth="25px"></a>&nbsp;&nbsp;<a href="edit.php" title="Modificar"><image src="iedit.png" width="25px" heigth="25px"></a>&nbsp;&nbsp;<a href="detalhes.php" title="Detalhes"><image src="idetalhes.png" width="25px" heigth="25px"></a></td></tr>
<tr class="odd"><th id="r99" scope="row">SALA TÉCNICA</th><td>OI</td><td>092</td><td>99999999</td><td><a href="delete.php" title="Excluir"><image src="idelete.png" width="25px" heigth="25px"></a>&nbsp;&nbsp;<a href="edit.php" title="Modificar"><image src="iedit.png" width="25px" heigth="25px"></a>&nbsp;&nbsp;<a href="detalhes.php" title="Detalhes"><image src="idetalhes.png" width="25px" heigth="25px"></a></td></tr>
<tr><th id="r98" scope="row">SALA TÉCNICA</th><td>OI</td><td>092</td><td>111111111</td><td><a href="delete.php" title="Excluir"><image src="idelete.png" width="25px" heigth="25px"></a>&nbsp;&nbsp;<a href="edit.php" title="Modificar"><image src="iedit.png" width="25px" heigth="25px"></a>&nbsp;&nbsp;<a href="detalhes.php" title="Detalhes"><image src="idetalhes.png" width="25px" heigth="25px"></a></td></tr>
<tr class="odd"><th id="r97" scope="row">SALA TÉCNICA</th><td>OI</td><td>092</td><td>77777777</td><td><a href="delete.php" title="Excluir"><image src="idelete.png" width="25px" heigth="25px"></a>&nbsp;&nbsp;<a href="edit.php" title="Modificar"><image src="iedit.png" width="25px" heigth="25px"></a>&nbsp;&nbsp;<a href="detalhes.php" title="Detalhes"><image src="idetalhes.png" width="25px" heigth="25px"></a></td></tr>
<tr><th id="r96" scope="row">SALA TÉCNICA</th><td>OI</td><td>092</td><td>666666666</td><td><a href="delete.php" title="Excluir"><image src="idelete.png" width="25px" heigth="25px"></a>&nbsp;&nbsp;<a href="edit.php" title="Modificar"><image src="iedit.png" width="25px" heigth="25px"></a>&nbsp;&nbsp;<a href="detalhes.php" title="Detalhes"><image src="idetalhes.png" width="25px" heigth="25px"></a></td></tr>
<tr class="odd"><th id="r95" scope="row">SALA TÉCNICA</th><td>OI</td><td>092</td><td>55555555</td><td><a href="delete.php" title="Excluir"><image src="idelete.png" width="25px" heigth="25px"></a>&nbsp;&nbsp;<a href="edit.php" title="Modificar"><image src="iedit.png" width="25px" heigth="25px"></a>&nbsp;&nbsp;<a href="detalhes.php" title="Detalhes"><image src="idetalhes.png" width="25px" heigth="25px"></a></td></tr>
<tr><th id="r93" scope="row">SALA TÉCNICA</th><td>OI</td><td>092</td><td>444444444</td><td><a href="delete.php" title="Excluir"><image src="idelete.png" width="25px" heigth="25px"></a>&nbsp;&nbsp;<a href="edit.php" title="Modificar"><image src="iedit.png" width="25px" heigth="25px"></a>&nbsp;&nbsp;<a href="detalhes.php" title="Detalhes"><image src="idetalhes.png" width="25px" heigth="25px"></a></td></tr>
</tbody></table><br><br><br>
